name: ticket_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  provider: ^6.1.2
  go_router: ^14.7.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  logger: ^2.5.0
  page_transition: ^2.1.0
  universal_platform: ^1.1.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


